Add weekly view
netceteragroup/pulse-eco-ios pull request #6
Opened 2021-02-17 11:29 UTC by MajaMitreska

2021-02-19 14:18 UTC, sardzoski commented
117 files changed... 😵

2021-02-19 15:07 UTC, sardzoski requested changes

2021-02-19 15:07 UTC, sardzoski commented on PulseEcoSwiftUI/PulseEcoSwiftUI/CityMap/SensorDetails/SenDetView.swift
> +                CollapsedView(viewModel: SensorDetailsVM(sensor: self.appVM.selectedSensor ?? SensorVM(),
Create the VM in the VM 😊

2021-02-19 15:07 UTC, sardzoski commented on PulseEcoSwiftUI/PulseEcoSwiftUI/CityMap/SensorDetails/SenDetView.swift
> +                        SensorDView(viewModel: ExpandedVM(sensorData24h: self.dataSource.sensorsData24h,
Same here. Also you can extract this closure in a separate variable or method in this file and just reference it.

2021-02-19 15:07 UTC, sardzoski commented on PulseEcoSwiftUI/PulseEcoSwiftUI/CityMap/SensorDetails/SenDetView.swift
> +            .offset(y: self.isExpanded ? UIHeight/2 - (self.expandedViewSize.height) + self.collapsedViewSize.height/2 : UIHeight/2 - (self.collapsedViewSize.height))
Make this calculation in the view model

2021-02-19 15:07 UTC, sardzoski commented on PulseEcoSwiftUI/PulseEcoSwiftUI/CityMap/SensorDetails/SenDetView.swift
> +                    .onEnded { value in
Extract this closure in a separate property and remove the unneeded code.

2021-02-19 15:07 UTC, sardzoski commented on PulseEcoSwiftUI/PulseEcoSwiftUI/CityMap/SensorDetails/SensorDView.swift
> +struct SensorDView: View {
Same comment about the name, view models, data, commented out code, view models and logic referenced from the view model, busy body 😊

2021-02-19 15:07 UTC, sardzoski commented on PulseEcoSwiftUI/PulseEcoSwiftUI/CityMap/SensorDetails/SensorDetailsView.swift
>  struct SensorDetailsView: View {
Same thing here as well.

2021-02-19 15:07 UTC, sardzoski commented on PulseEcoSwiftUI/PulseEcoSwiftUI/Constants.swift
> +let privacyPolicyLink = "https://www.netcetera.com/home/privacy-policy.html"
Here is the config 😊

2021-02-19 15:07 UTC, sardzoski commented on PulseEcoSwiftUI/PulseEcoSwiftUI/PartialViews/PartialSheetManager.swift
> +
Remove the extra lines

2021-02-19 15:07 UTC, sardzoski commented on PulseEcoSwiftUI/PulseEcoSwiftUI/PartialViews/PartialSheetManager.swift
> +public class PartialSheetManager: ObservableObject {
This looks copied from StackOverflow :D

2021-02-19 15:07 UTC, sardzoski commented on PulseEcoSwiftUI/PulseEcoSwiftUI/SceneDelegate.swift
> +         let sheetManager: PartialSheetManager = PartialSheetManager()
Wow, I hate this so much. But don't change this now

2021-03-24 18:20 UTC, marko-mni commented
Even tough there is a lot of work left for refactoring, we will merge this now to complete the internship goals and then I will refactor it.

2021-03-24 18:20 UTC, merged